package com.ffxiv_fansite.fansite.model;

import lombok.Getter;

@Getter
public enum Aetheryte {
    LIMSA_LOMINSA_LOWER_DECKS("Limsa Lominsa Lower Decks", Zone.LIMSA_LOMINSA_LOWER_DECKS),
    SUMMERFORD_FARMS("Summerford Farms", Zone.MIDDLE_LA_NOSCEA),
    MORABY_DRYDOCKS("Moraby Drydocks", Zone.LOWER_LA_NOSCEA),
    COSTA_DEL_SOL("Costa del Sol", Zone.EASTERN_LA_NOSCEA),
    WINEPORT("Wineport", Zone.EASTERN_LA_NOSCEA),
    SWIFTPERCH("Swiftperch", Zone.WESTERN_LA_NOSCEA),
    ALEPORT("Aleport", Zone.WESTERN_LA_NOSCEA),
    CAMP_BRONZE_LAKE("Camp Bronze Lake", Zone.UPPER_LA_NOSCEA),
    CAMP_OVERLOOK("Camp Overlook", Zone.OUTER_LA_NOSCEA),
    WOLVES_DEN_PIER("Wolves' Den Pier", Zone.WOLVES_DEN_PIER),
    NEW_GRIDANIA("New Gridania", Zone.NEW_GRIDANIA),
    BENTBRANCH_MEADOWS("Bentbranch Meadows", Zone.CENTRAL_SHROUD),
    THE_HAWTHORNE_HUT("The Hawthorne Hut", Zone.EAST_SHROUD),
    QUARRYMILL("Quarrymill", Zone.SOUTH_SHROUD),
    CAMP_TRANQUIL("Camp Tranquil", Zone.SOUTH_SHROUD),
    FALLGOURD_FLOAT("Fallgourd Float", Zone.NORTH_SHROUD),
    ULDAH_STEPS_OF_NALD("Ul'dah - Steps of Nald", Zone.ULDAH_STEPS_OF_NALD),
    HORIZON("Horizon", Zone.WESTERN_THANALAN),
    BLACK_BRUSH_STATION("Black Brush Station", Zone.CENTRAL_THANALAN),
    CAMP_DRYBONE("Camp Drybone", Zone.EASTERN_THANALAN),
    LITTLE_ALA_MHIGO("Little Ala Mhigo", Zone.SOUTHERN_THANALAN),
    FORGOTTEN_SPRINGS("Forgotten Springs", Zone.SOUTHERN_THANALAN),
    CAMP_BLUEFOG("Camp Bluefog", Zone.NORTHERN_THANALAN),
    CERULEUM_PROCESSING_PLANT("Ceruleum Processing Plant", Zone.NORTHERN_THANALAN),
    THE_GOLD_SAUCER("The Gold Saucer", Zone.THE_GOLD_SAUCER),
    FOUNDATION("Foundation", Zone.FOUNDATION),
    CAMP_DRAGONHEAD("Camp Dragonhead", Zone.COERTHAS_CENTRAL_HIGHLANDS),
    FALCONS_NEST("Falcon's Nest", Zone.COERTHAS_WESTERN_HIGHLANDS),
    CAMP_CLOUDTOP("Camp Cloudtop", Zone.THE_SEA_OF_CLOUDS),
    OK_ZUNDU("Ok' Zundu", Zone.THE_SEA_OF_CLOUDS),
    HELIX("Helix", Zone.AZYS_LLA),
    IDYLLSHIRE("Idyllshire", Zone.IDYLLSHIRE),
    TAILFEATHER("Tailfeather", Zone.THE_DRAVANIAN_FORELANDS),
    ANYX_TRINE("Anyx Trine", Zone.THE_DRAVANIAN_FORELANDS),
    MOGHOME("Moghome", Zone.THE_CHURNING_MISTS),
    ZENITH("Zenith", Zone.THE_CHURNING_MISTS),
    RHALGRS_REACH("Rhalgr's Reach", Zone.RHALGRS_REACH),
    CASTRUM_ORIENS("Castrum Oriens", Zone.THE_FRINGES),
    THE_PEERING_STONES("The Peering Stones", Zone.THE_FRINGES),
    ALA_GANNHA("Ala Gannha", Zone.THE_PEAKS),
    ALA_GHIRI("Ala Ghiri", Zone.THE_PEAKS),
    PORTA_PRAETORIA("Porta Praetoria", Zone.THE_LOCHS),
    THE_ALA_MHIGAN_QUARTER("The Ala Mhigan Quarter", Zone.THE_LOCHS),
    KUGANE("Kugane", Zone.KUGANE),
    TAMAMIZU("Tamamizu", Zone.THE_RUBY_SEA),
    ONOKORO("Onokoro", Zone.THE_RUBY_SEA),
    NAMAI("Namai", Zone.YANXIA),
    THE_HOUSE_OF_THE_FIERCE("The House of the Fierce", Zone.YANXIA),
    REUNION("Reunion", Zone.THE_AZIM_STEPPE),
    THE_DAWN_THRONE("The Dawn Throne", Zone.THE_AZIM_STEPPE),
    DHORO_ILOH("Dhoro Iloh", Zone.THE_AZIM_STEPPE),
    THE_DOMAN_ENCLAVE("The Doman Enclave", Zone.THE_DOMAN_ENCLAVE),
    RADZ_AT_HAN("Radz-at-Han", Zone.RADZ_AT_HAN),
    YEDLIHMAD("Yedlihmad", Zone.THAVNAIR),
    THE_GREAT_WORK("The Great Work", Zone.THAVNAIR),
    PALAKAS_STAND("Palaka's Stand", Zone.THAVNAIR),
    CAMP_BROKEN_GLASS("Camp Broken Glass", Zone.GARLEMALD),
    TERTIUM("Tertium", Zone.GARLEMALD),
    THE_CRYSTARIUM("The Crystarium", Zone.THE_CRYSTARIUM),
    EULMORE("Eulmore", Zone.EULMORE),
    FORT_JOBB("Fort Jobb", Zone.LAKELAND),
    THE_OSTALL_IMPERATIVE("The Ostall Imperative", Zone.LAKELAND),
    STILLTIDE("Stilltide", Zone.KHOLUSIA),
    WRIGHT("Wright", Zone.KHOLUSIA),
    TOMRA("Tomra", Zone.KHOLUSIA),
    MORD_SOUQ("Mord Souq", Zone.AMH_ARAENG),
    THE_INN_AT_JOURNEYS_HEAD("The Inn at Journey's Head", Zone.AMH_ARAENG),
    TWINE("Twine", Zone.AMH_ARAENG),
    LYDHA_LRAN("Lydha Lran", Zone.IL_MHEG),
    PLA_ENNI("Pla Enni", Zone.IL_MHEG),
    WOLEKDORF("Wolekdorf", Zone.IL_MHEG),
    SLITHERBOUGH("Slitherbough", Zone.THE_RAKTIKA_GREATWOOD),
    FANOW("Fanow", Zone.THE_RAKTIKA_GREATWOOD),
    THE_ONDO_CUPS("The Ondo Cups", Zone.THE_TEMPEST),
    THE_MACARENSES_ANGLE("The Macarenses Angle", Zone.THE_TEMPEST),
    REVENANTS_TOLL("Revenant's Toll", Zone.MOR_DHONA),
    OLD_SHARLAYAN("Old Sharlayan", Zone.OLD_SHARLAYAN),
    THE_ARCHEION("The Archeion", Zone.LABYRINTHOS),
    SHARLAYAN_HAMLET("Sharlayan Hamlet", Zone.LABYRINTHOS),
    APORIA("Aporia", Zone.LABYRINTHOS),
    SINUS_LACRIMARUM("Sinus Lacrimarum", Zone.MARE_LAMENTORUM),
    BESTWAYS_BURROW("Bestways Burrow", Zone.MARE_LAMENTORUM),
    REAH_TAHRA("Reah Tahra", Zone.ULTIMA_THULE),
    ABODE_OF_THE_EA("Abode of the Ea", Zone.ULTIMA_THULE),
    BASE_OMICRON("Base Omicron", Zone.ULTIMA_THULE),
    ANAGNORISIS("Anagnorisis", Zone.ELPIS),
    THE_TWELVE_WONDERS("The Twelve Wonders", Zone.ELPIS),
    POIETEN_OIKOS("Poieten Oikos", Zone.ELPIS),
    TULIYOLLAL("Tuliyollal", Zone.TULIYOLLAL),
    WACHUNPELO("Wachunpelo", Zone.URQOPACHA),
    WORLARS_ECHO("Worlar's Echo", Zone.URQOPACHA),
    OKHANU("Ok'hanu", Zone.KOZAMAUKA),
    MANY_FIRES("Many Fires", Zone.KOZAMAUKA),
    EARTHENSHIRE("Earthenshire", Zone.KOZAMAUKA),
    DOCK_POGA("Dock Poga", Zone.KOZAMAUKA),
    IQ_BRAAX("Iq Br'aax", Zone.YAK_TEL),
    MAMOOK("Mamook", Zone.YAK_TEL),
    HHUSATAHWI("Hhusatahwi", Zone.SHAALOANI),
    SHESHENEWEZI_SPRINGS("Sheshenewezi Springs", Zone.SHAALOANI),
    MEHWAHHETSOAN("Mehwahhetsoan", Zone.SHAALOANI),
    YYASULANI_STATION("Yyasulani Station", Zone.HERITAGE_FOUND),
    THE_OUTSKIRTS("The Outskirts", Zone.HERITAGE_FOUND),
    ELECTROPE_STRIKE("Electrope Strike", Zone.HERITAGE_FOUND),
    SOLUTION_NINE("Solution Nine", Zone.SOLUTION_NINE),
    LEYNODE_MNEMO("Leynode Mnemo", Zone.LIVING_MEMORY),
    LEYNODE_PYRO("Leynode Pyro", Zone.LIVING_MEMORY),
    LEYNODE_AERO("Leynode Aero", Zone.LIVING_MEMORY);

    private final String name;
    private final Zone zone;

    Aetheryte(final String name, final Zone zone) {
        this.name = name;
        this.zone = zone;
    }
}
